#:kivy 1.0.9

<PongGame>:    
    canvas:
        Rectangle:
            pos: self.center_x - 10, 0
            size: 5, self.height
            
    Label:
        font_size: 70  
        center_x: root.width / 5
        top: root.top - 50
        text: "Welcome"

    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: "Kivy"

